# OLOG Data Retriever

In [1]:
import matplotlib.pyplot as plt
import requests
import pandas as pd
import xml.etree.ElementTree as ET

In [47]:
url = "https://ais-eng-srv-ca.cnpem.br/Olog/resources/logs"

paramaters = {
    "search": "*terremoto*",
    "sort": "created",
    "page": 1,
    "limit": 400,
}

response = requests.get(url, params=paramaters)

df = pd.json_normalize(response.json())

df = df.reindex(["id", "version", "owner", "createdDate", "eventStart", "description", "attachments"],axis=1)

paramaters = {
    "search": "*sísmico*",
    "sort": "created",
    "page": 1,
    "limit": 400,
}

response = requests.get(url, params=paramaters)

df_2 = pd.json_normalize(response.json())

df_2 = df_2.reindex(["id", "version", "owner", "createdDate", "eventStart", "description", "attachments"],axis=1)

df = pd.concat([df, df_2], axis=0, ignore_index=True).drop_duplicates("id")

df.to_csv("olog_data.csv", index=False)

df

,id,version,owner,createdDate,eventStart,description,attachments
0,34292,2,alex.cavalcante,1791606683000,1791579600000,**Oscilaçôes no feixe devido a abalos sísmicos...,"[{'fileName': 'QUAKE DETAILS.png', 'contentTyp..."
1,34291,1,vanusa.souza,1791580202000,1791580202000,### **Turno de usuários**\n\n\n\n\n- 04h23: Oc...,[]
2,34284,4,wagner.bento,1791575366000,1791570239000,#### Oscilação no feixe devido a ocorrencia de...,[{'fileName': 'Screenshot from 2026-10-09 16-2...
3,33387,2,vanusa.souza,1787257212000,1787257212000,##### **Oscilaçôes no feixe- possível influênc...,[{'fileName': 'Screenshot from 2026-08-20 16-1...
4,33338,1,alex.cavalcante,1786782933000,1786752000000,**Oscilaçôes no feixe devido a abalos sísmicos...,"[{'fileName': 'QUAKE_INDONESIA.png', 'contentT..."
5,33266,5,lucas.ransato,1786392909000,1786365268000,"**Terremoto na Colômbia - San José del Palmar,...",[{'fileName': 'Screenshot from 2026-08-10 17-1...
6,33005,6,daniel.cantarani,1785241701000,1785241701000,### Terremoto no Japão\n.\n- Por volta de 07h4...,[{'fileName': 'SismÃ³grafo terremoto Japan.PNG...
7,32807,2,wagner.bento,1784309897000,1784309897000,**TERREMOTO - EVENTO SÍSMICO DETECTADO** \n\n-...,[{'fileName': 'Screenshot from 2026-07-17 14-3...
8,32454,6,carlos.vieira,1782374640000,1782374640000,### Oscilações no feixe por Abalos Sísmicos\n'...,"[{'fileName': 'image_1782374640200.png', 'cont..."
9,32189,3,alex.cavalcante,1780908433000,1780880400000,**Oscilaçôes no feixe por abalos sísmicos**\n\...,"[{'fileName': 'quake0706.png', 'contentType': ..."
10,30916,4,wagner.bento,1774000537000,1773972000000,#### Oscilaçôes no feixe por abalos sísmicos\n...,"[{'fileName': 'quake.PNG', 'contentType': 'ima..."
11,30766,5,vanusa.souza,1773419114000,1773419113000,##### **TERREMOTO - EVENTO SÍSMICO DETECTADO ...,"[{'fileName': 'Capturar.PNG', 'contentType': '..."
12,28551,4,alex.cavalcante,1758779994000,1758772800000,## Terremoto 2 (Venezuela)\nNovo terremoto na ...,[{'fileName': 'Screenshot 2025-09-25 at 03-32-...
13,28549,3,alex.cavalcante,1758758030000,1758753722000,## Terremoto (Venezuela)\nOs BPMs apresentaram...,"[{'fileName': 'quakeVen.PNG', 'contentType': '..."
14,28375,1,alex.cavalcante,1757758631000,1757736840000,"Entre 00h52 e 01h15, os BPMs horizontais apres...",[{'fileName': 'Screenshot 2025-09-13 at 06-59-...
15,28009,5,vanusa.souza,1755834161000,1755834160000,"- Entre 23h30 e 23h55, os BPMs horizontais apr...",[{'fileName': 'Screenshot 2025-08-22 at 00-37-...
16,27663,2,wagner.bento,1753848445000,1753839300000,"Durante os estudos de máquina, pessoal do grup...",[{'fileName': 'Screenshot from 2025-07-30 01-0...
17,27213,3,vanusa.souza,1751110563000,1751110563000,Houve pertubações nos BPMs do Anel nos planos ...,[{'fileName': 'Screenshot%20from%202025-06-28%...
18,26531,3,wagner.bento,1746213283000,1746190680000,Tivemos pequenas pertubações na órbita do feix...,[{'fileName': 'Screenshot from 2025-05-02 16-1...
19,26528,4,wagner.bento,1746195497000,1746195497000,### Turno de Usuários:\n'\n+ **09h45:** Terrem...,[{'fileName': 'Screenshot from 2025-05-02 12-2...
20,25307,4,carlos.vieira,1739074035000,1739074035000,### Pertubações na órbita Horizontal e Vertica...,"[{'fileName': 'BPMs.jpg', 'contentType': 'imag..."
21,24692,3,alex.cavalcante,1734167413000,1734133273000,"Entre 20h43 e 21h00, os BPMs horizontais apres...","[{'fileName': 'earthquake.jpg', 'contentType':..."
22,22946,4,wagner.bento,1721360690000,1721354100000,Houve pertubações nos [**BPMs**](https://ais-e...,[{'fileName': 'Sis_Chile_BPMs_OrbXY_180724.JPG...
23,22785,2,alex.cavalcante,1719656186000,1719645720000,Entre 04h22 E 04h28 alguns setores de bpms ho...,[{'fileName': 'Captura de tela 2024-06-29 0714...
35,30585,2,wagner.bento,1772132207000,1772132207000,O sismografo do túnel do Anel registrou um peq...,[{'fileName': 'Screenshot%20from%202026-02-26%...
36,29076,2,wagner.bento,1761955456000,1761936446000,"Houve um pequeno abalo sísmico, os [**BPMs do ...",[{'fileName': 'Screenshot%20from%202025-10-31%...
38,28472,3,walter.junior,1758388544000,1758225900000,"## Anotação tardia##\nSegue em anexo, gráficos...",[{'fileName': 'Screenshot%20from%202025-09-20%...
41,27665,6,wagner.bento,1753850224000,1753850224000,### Turno de Estudos de Máquina:\n'\n+ **19h02...,[]
44,24582,2,wagner.bento,1733434240000,1733434239000,Observamos pequenas pertubações nos dois plano...,"[{'fileName': 'sisimografo_051224.pdf', 'conte..."
45,22953,1,wagner.bento,1721363213000,1721363213000,### Turno de Operação:\n'\n+ **21h00:** Reboot...,[]

In [3]:
# !pip install openai

In [26]:
import getpass
from openai import OpenAI
import time
from datetime import datetime, timezone

In [6]:
# BASE_URL = "https://iluma.cnpem.br:4000/v1/"
# API_KEY = getpass.getpass("Insira a chave API: ")
# MODEL_NAME = "iluma"

BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai/"
API_KEY = getpass.getpass("Insira a chave API: ")
MODEL_NAME = "models/gemini-3.5-flash-lite"

In [7]:
client = OpenAI(
    base_url=BASE_URL, 
    api_key=API_KEY
)

response = client.chat.completions.create(
    model=MODEL_NAME,
    messages=[
        {
            "role": "user",
            "content": "Olá"
        }
    ]
)

print(response.choices[0].message.content)

Olá! Como posso ajudar você hoje?

In [12]:
SYSTEM_PROMPT = """
You are a timestamp extraction engine.

TASK
Extract the event start and end times from the provided log.

INPUT

You will receive:
- Reference date (YYYY-MM-DD)
- Log text

RULES

1. Use ONLY information present in the log.
2. The reference date must always be used when a time appears without a date.
3. Assume timestamps are GMT-3 unless another timezone is explicitly specified.
4. Convert all timestamps to UTC.
5. Return timestamps in ISO 8601 format:
   YYYY-MM-DDTHH:MM:SS.000000Z

6. If an explicit time interval is found:
   - first time -> from
   - second time -> to

7. If only a single timestamp is found:
   - set "from" to that timestamp
   - set "to" to exactly 2 hours after "from"

8. If multiple timestamps are mentioned but they do not explicitly define an interval:
   - use the earliest timestamp as "from"
   - use the latest timestamp as "to"

9. If no timestamp can be determined:
   - from = null
   - to = null

10. Never return explanations.
11. Never return examples.
12. Never repeat the input.
13. Never return markdown.
14. Return only a valid JSON object.
15. All timestamps must always contain a complete ISO 8601 UTC datetime.

OUTPUT FORMAT

{
  "from": string | null,
  "to": string | null
}
"""

def get_times_from_description(log_text):
    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": log_text
            }
        ],
        response_format={"type": "json_object"}
    )
    
    return response.choices[0].message.content

print(get_times_from_description(df.loc[0]["description"]))

{
  "from": "2024-06-05T20:25:00.000000Z",
  "to": "2024-06-05T21:00:00.000000Z"
}

In [28]:
times_from_logs = []

for i, log in df.iterrows():
    ts = float(log["eventStart"]) / 1000

    iso = datetime.fromtimestamp(
        ts,
        tz=timezone.utc
    ).strftime("%Y-%m-%dT%H:%M:%S.000000Z")

    print(f"LOG {i:2} - {log["id"]}: Processando descrição...")
    start_time = time.time()
    response = get_times_from_description(f"Reference Date: {iso} | Description: {log["description"]}")
    delta_time = time.time() - start_time
    print(f"LOG {i:2} - {log["id"]}: Processado em {delta_time:.2f}s")
    print(response)
    time.sleep(6)
    
    times_from_logs.append(response)

LOG  0 - 34292: Processando descrição...
LOG  0 - 34292: Processado em 18.24s
{
  "from": "2026-10-09T20:25:00.000000Z",
  "to": "2026-10-09T21:00:00.000000Z"
}
LOG  1 - 34291: Processando descrição...
LOG  1 - 34291: Processado em 8.36s
{
  "from": "2026-10-09T07:23:00.000000Z",
  "to": "2026-10-09T10:41:00.000000Z"
}
LOG  2 - 34284: Processando descrição...
LOG  2 - 34284: Processado em 16.83s
{
  "from": "2026-10-09T18:13:37.000000Z",
  "to": "2026-10-09T18:23:59.000000Z"
}
LOG  3 - 33387: Processando descrição...
LOG  3 - 33387: Processado em 10.59s
{
  "from": "2026-08-20T18:00:00.000000Z",
  "to": "2026-08-20T20:00:00.000000Z"
}
LOG  4 - 33338: Processando descrição...
LOG  4 - 33338: Processado em 9.40s
{
  "from": "2026-08-15T22:00:00.000000Z",
  "to": "2026-08-16T00:00:00.000000Z"
}
LOG  5 - 33266: Processando descrição...
LOG  5 - 33266: Processado em 7.48s
{
  "from": "2026-08-10T12:34:28.000000Z",
  "to": "2026-08-10T14:34:28.000000Z"
}
LOG  6 - 33005: Processando descrição...
LOG  6 - 33005: Processado em 9.79s
{
  "from": "2026-07-28T07:27:00.000000Z",
  "to": "2026-07-28T09:27:00.000000Z"
}
LOG  7 - 32807: Processando descrição...
LOG  7 - 32807: Processado em 9.42s
{
  "from": "2026-07-17T15:06:00.000000Z",
  "to": "2026-07-17T15:47:00.000000Z"
}
LOG  8 - 32454: Processando descrição...
LOG  8 - 32454: Processado em 7.58s
{
  "from": null,
  "to": null
}
LOG  9 - 32189: Processando descrição...
LOG  9 - 32189: Processado em 16.94s
{
  "from": "2026-06-08T23:37:00.000000Z",
  "to": "2026-06-09T01:37:00.000000Z"
}
LOG 10 - 30916: Processando descrição...
LOG 10 - 30916: Processado em 7.13s
{
  "from": "2026-03-21T00:22:00.000000Z",
  "to": "2026-03-21T01:15:00.000000Z"
}
LOG 11 - 30766: Processando descrição...
LOG 11 - 30766: Processado em 15.10s
{
  "from": "2026-03-13T13:49:00.000000Z",
  "to": "2026-03-13T13:55:00.000000Z"
}
LOG 12 - 28551: Processando descrição...
LOG 12 - 28551: Processado em 14.94s
{
  "from": "2025-09-25T03:58:00.000000Z",
  "to": "2025-09-25T05:58:00.000000Z"
}
LOG 13 - 28549: Processando descrição...
LOG 13 - 28549: Processado em 6.79s
{
  "from": "2025-09-24T22:18:00.000000Z",
  "to": "2025-09-24T22:42:00.000000Z"
}
LOG 14 - 28375: Processando descrição...
LOG 14 - 28375: Processado em 13.45s
{
  "from": "2025-09-13T03:52:00.000000Z",
  "to": "2025-09-13T04:15:00.000000Z"
}
LOG 15 - 28009: Processando descrição...
LOG 15 - 28009: Processado em 9.41s
{
  "from": "2025-08-23T02:16:00.000000Z",
  "to": "2025-08-23T02:55:00.000000Z"
}
LOG 16 - 27663: Processando descrição...
LOG 16 - 27663: Processado em 6.71s
{
  "from": "2025-07-30T04:36:01.597000Z",
  "to": "2025-07-30T04:46:01.597000Z"
}
LOG 17 - 27213: Processando descrição...
LOG 17 - 27213: Processado em 6.45s
{
  "from": "2025-06-28T08:32:00.000000Z",
  "to": "2025-06-28T10:32:00.000000Z"
}
LOG 18 - 26531: Processando descrição...
LOG 18 - 26531: Processado em 6.38s
{
  "from": "2025-05-02T13:02:10.500000Z",
  "to": "2025-05-02T14:02:10.500000Z"
}
LOG 19 - 26528: Processando descrição...
LOG 19 - 26528: Processado em 11.47s
{
  "from": "2025-05-02T12:45:00.000000Z",
  "to": "2025-05-02T17:00:00.000000Z"
}
LOG 20 - 25307: Processando descrição...
LOG 20 - 25307: Processado em 14.10s
{
  "from": "2025-02-09T23:23:00.000000Z",
  "to": "2025-02-09T23:40:00.000000Z"
}
LOG 21 - 24692: Processando descrição...
LOG 21 - 24692: Processado em 4.06s
{
  "from": "2024-12-13T23:43:00.000000Z",
  "to": "2024-12-14T00:00:00.000000Z"
}
LOG 22 - 22946: Processando descrição...
LOG 22 - 22946: Processado em 9.91s
{
  "from": "2024-07-19T01:54:13.886Z",
  "to": "2024-07-19T01:59:13.886Z"
}
LOG 23 - 22785: Processando descrição...
LOG 23 - 22785: Processado em 9.01s
{
  "from": "2024-06-29T07:22:00.000000Z",
  "to": "2024-06-29T07:28:00.000000Z"
}
LOG 35 - 30585: Processando descrição...
LOG 35 - 30585: Processado em 7.78s
{
  "from": null,
  "to": null
}
LOG 36 - 29076: Processando descrição...
LOG 36 - 29076: Processado em 5.87s
{
  "from": null,
  "to": null
}
LOG 38 - 28472: Processando descrição...
LOG 38 - 28472: Processado em 7.00s
{
  "from": null,
  "to": null
}
LOG 41 - 27665: Processando descrição...
LOG 41 - 27665: Processado em 5.45s
{
  "from": "2025-07-30T22:02:00.000000Z",
  "to": "2025-07-30T09:20:00.000000Z"
}
LOG 44 - 24582: Processando descrição...
LOG 44 - 24582: Processado em 6.90s
{
  "from": null,
  "to": null
}
LOG 45 - 22953: Processando descrição...
LOG 45 - 22953: Processado em 8.07s
{
  "from": "2024-07-20T00:00:00.000000Z",
  "to": "2024-07-20T02:06:00.000000Z"
}

In [31]:
import json

In [38]:
json_times_from_logs = [json.loads(x) for x in times_from_logs]
json_times_from_logs

[{'from': '2026-10-09T20:25:00.000000Z', 'to': '2026-10-09T21:00:00.000000Z'},
 {'from': '2026-10-09T07:23:00.000000Z', 'to': '2026-10-09T10:41:00.000000Z'},
 {'from': '2026-10-09T18:13:37.000000Z', 'to': '2026-10-09T18:23:59.000000Z'},
 {'from': '2026-08-20T18:00:00.000000Z', 'to': '2026-08-20T20:00:00.000000Z'},
 {'from': '2026-08-15T22:00:00.000000Z', 'to': '2026-08-16T00:00:00.000000Z'},
 {'from': '2026-08-10T12:34:28.000000Z', 'to': '2026-08-10T14:34:28.000000Z'},
 {'from': '2026-07-28T07:27:00.000000Z', 'to': '2026-07-28T09:27:00.000000Z'},
 {'from': '2026-07-17T15:06:00.000000Z', 'to': '2026-07-17T15:47:00.000000Z'},
 {'from': None, 'to': None},
 {'from': '2026-06-08T23:37:00.000000Z', 'to': '2026-06-09T01:37:00.000000Z'},
 {'from': '2026-03-21T00:22:00.000000Z', 'to': '2026-03-21T01:15:00.000000Z'},
 {'from': '2026-03-13T13:49:00.000000Z', 'to': '2026-03-13T13:55:00.000000Z'},
 {'from': '2025-09-25T03:58:00.000000Z', 'to': '2025-09-25T05:58:00.000000Z'},
 {'from': '2025-09-24T22:18:00.000000Z', 'to': '2025-09-24T22:42:00.000000Z'},
 {'from': '2025-09-13T03:52:00.000000Z', 'to': '2025-09-13T04:15:00.000000Z'},
 {'from': '2025-08-23T02:16:00.000000Z', 'to': '2025-08-23T02:55:00.000000Z'},
 {'from': '2025-07-30T04:36:01.597000Z', 'to': '2025-07-30T04:46:01.597000Z'},
 {'from': '2025-06-28T08:32:00.000000Z', 'to': '2025-06-28T10:32:00.000000Z'},
 {'from': '2025-05-02T13:02:10.500000Z', 'to': '2025-05-02T14:02:10.500000Z'},
 {'from': '2025-05-02T12:45:00.000000Z', 'to': '2025-05-02T17:00:00.000000Z'},
 {'from': '2025-02-09T23:23:00.000000Z', 'to': '2025-02-09T23:40:00.000000Z'},
 {'from': '2024-12-13T23:43:00.000000Z', 'to': '2024-12-14T00:00:00.000000Z'},
 {'from': '2024-07-19T01:54:13.886Z', 'to': '2024-07-19T01:59:13.886Z'},
 {'from': '2024-06-29T07:22:00.000000Z', 'to': '2024-06-29T07:28:00.000000Z'},
 {'from': None, 'to': None},
 {'from': None, 'to': None},
 {'from': None, 'to': None},
 {'from': '2025-07-30T22:02:00.000000Z', 'to': '2025-07-30T09:20:00.000000Z'},
 {'from': None, 'to': None},
 {'from': '2024-07-20T00:00:00.000000Z', 'to': '2024-07-20T02:06:00.000000Z'}]

In [ ]:
df["from"] = [x["from"] for x in json_times_from_logs]
df["to"] = [x["to"] for x in json_times_from_logs]
df.to_csv("olog_data.csv", index=False)

df

,id,version,owner,createdDate,eventStart,description,attachments,from,to
0,34292,2,alex.cavalcante,1791606683000,1791579600000,**Oscilaçôes no feixe devido a abalos sísmicos...,"[{'fileName': 'QUAKE DETAILS.png', 'contentTyp...",2026-10-09T20:25:00.000000Z,2026-10-09T21:00:00.000000Z
1,34291,1,vanusa.souza,1791580202000,1791580202000,### **Turno de usuários**\n\n\n\n\n- 04h23: Oc...,[],2026-10-09T07:23:00.000000Z,2026-10-09T10:41:00.000000Z
2,34284,4,wagner.bento,1791575366000,1791570239000,#### Oscilação no feixe devido a ocorrencia de...,[{'fileName': 'Screenshot from 2026-10-09 16-2...,2026-10-09T18:13:37.000000Z,2026-10-09T18:23:59.000000Z
3,33387,2,vanusa.souza,1787257212000,1787257212000,##### **Oscilaçôes no feixe- possível influênc...,[{'fileName': 'Screenshot from 2026-08-20 16-1...,2026-08-20T18:00:00.000000Z,2026-08-20T20:00:00.000000Z
4,33338,1,alex.cavalcante,1786782933000,1786752000000,**Oscilaçôes no feixe devido a abalos sísmicos...,"[{'fileName': 'QUAKE_INDONESIA.png', 'contentT...",2026-08-15T22:00:00.000000Z,2026-08-16T00:00:00.000000Z
5,33266,5,lucas.ransato,1786392909000,1786365268000,"**Terremoto na Colômbia - San José del Palmar,...",[{'fileName': 'Screenshot from 2026-08-10 17-1...,2026-08-10T12:34:28.000000Z,2026-08-10T14:34:28.000000Z
6,33005,6,daniel.cantarani,1785241701000,1785241701000,### Terremoto no Japão\n.\n- Por volta de 07h4...,[{'fileName': 'SismÃ³grafo terremoto Japan.PNG...,2026-07-28T07:27:00.000000Z,2026-07-28T09:27:00.000000Z
7,32807,2,wagner.bento,1784309897000,1784309897000,**TERREMOTO - EVENTO SÍSMICO DETECTADO** \n\n-...,[{'fileName': 'Screenshot from 2026-07-17 14-3...,2026-07-17T15:06:00.000000Z,2026-07-17T15:47:00.000000Z
8,32454,6,carlos.vieira,1782374640000,1782374640000,### Oscilações no feixe por Abalos Sísmicos\n'...,"[{'fileName': 'image_1782374640200.png', 'cont...",None,None
9,32189,3,alex.cavalcante,1780908433000,1780880400000,**Oscilaçôes no feixe por abalos sísmicos**\n\...,"[{'fileName': 'quake0706.png', 'contentType': ...",2026-06-08T23:37:00.000000Z,2026-06-09T01:37:00.000000Z
10,30916,4,wagner.bento,1774000537000,1773972000000,#### Oscilaçôes no feixe por abalos sísmicos\n...,"[{'fileName': 'quake.PNG', 'contentType': 'ima...",2026-03-21T00:22:00.000000Z,2026-03-21T01:15:00.000000Z
11,30766,5,vanusa.souza,1773419114000,1773419113000,##### **TERREMOTO - EVENTO SÍSMICO DETECTADO ...,"[{'fileName': 'Capturar.PNG', 'contentType': '...",2026-03-13T13:49:00.000000Z,2026-03-13T13:55:00.000000Z
12,28551,4,alex.cavalcante,1758779994000,1758772800000,## Terremoto 2 (Venezuela)\nNovo terremoto na ...,[{'fileName': 'Screenshot 2025-09-25 at 03-32-...,2025-09-25T03:58:00.000000Z,2025-09-25T05:58:00.000000Z
13,28549,3,alex.cavalcante,1758758030000,1758753722000,## Terremoto (Venezuela)\nOs BPMs apresentaram...,"[{'fileName': 'quakeVen.PNG', 'contentType': '...",2025-09-24T22:18:00.000000Z,2025-09-24T22:42:00.000000Z
14,28375,1,alex.cavalcante,1757758631000,1757736840000,"Entre 00h52 e 01h15, os BPMs horizontais apres...",[{'fileName': 'Screenshot 2025-09-13 at 06-59-...,2025-09-13T03:52:00.000000Z,2025-09-13T04:15:00.000000Z
15,28009,5,vanusa.souza,1755834161000,1755834160000,"- Entre 23h30 e 23h55, os BPMs horizontais apr...",[{'fileName': 'Screenshot 2025-08-22 at 00-37-...,2025-08-23T02:16:00.000000Z,2025-08-23T02:55:00.000000Z
16,27663,2,wagner.bento,1753848445000,1753839300000,"Durante os estudos de máquina, pessoal do grup...",[{'fileName': 'Screenshot from 2025-07-30 01-0...,2025-07-30T04:36:01.597000Z,2025-07-30T04:46:01.597000Z
17,27213,3,vanusa.souza,1751110563000,1751110563000,Houve pertubações nos BPMs do Anel nos planos ...,[{'fileName': 'Screenshot%20from%202025-06-28%...,2025-06-28T08:32:00.000000Z,2025-06-28T10:32:00.000000Z
18,26531,3,wagner.bento,1746213283000,1746190680000,Tivemos pequenas pertubações na órbita do feix...,[{'fileName': 'Screenshot from 2025-05-02 16-1...,2025-05-02T13:02:10.500000Z,2025-05-02T14:02:10.500000Z
19,26528,4,wagner.bento,1746195497000,1746195497000,### Turno de Usuários:\n'\n+ **09h45:** Terrem...,[{'fileName': 'Screenshot from 2025-05-02 12-2...,2025-05-02T12:45:00.000000Z,2025-05-02T17:00:00.000000Z
20,25307,4,carlos.vieira,1739074035000,1739074035000,### Pertubações na órbita Horizontal e Vertica...,"[{'fileName': 'BPMs.jpg', 'contentType': 'imag...",2025-02-09T23:23:00.000000Z,2025-02-09T23:40:00.000000Z
21,24692,3,alex.cavalcante,1734167413000,1734133273000,"Entre 20h43 e 21h00, os BPMs horizontais apres...","[{'fileName': 'earthquake.jpg', 'contentType':...",2024-12-13T23:43:00.000000Z,2024-12-14T00:00:00.000000Z
22,22946,4,wagner.bento,1721360690000,1721354100000,Houve pertubações nos [**BPMs**](https://ais-e...,[{'fileName': 'Sis_Chile_BPMs_OrbXY_180724.JPG...,2024-07-19T01:54:13.886Z,2024-07-19T01:59:13.886Z
23,22785,2,alex.cavalcante,1719656186000,1719645720000,Entre 04h22 E 04h28 alguns setores de bpms ho...,[{'fileName': 'Captura de tela 2024-06-29 0714...,2024-06-29T07:22:00.000000Z,2024-06-29T07:28:00.000000Z
35,30585,2,wagner.bento,1772132207000,1772132207000,O sismografo do túnel do Anel registrou um peq...,[{'fileName': 'Screenshot%20from%202026-02-26%...,None,None
36,29076,2,wagner.bento,1761955456000,1761936446000,"Houve um pequeno abalo sísmico, os [**BPMs do ...",[{'fileName': 'Screenshot%20from%202025-10-31%...,None,None
38,28472,3,walter.junior,1758388544000,1758225900000,"## Anotação tardia##\nSegue em anexo, gráficos...",[{'fileName': 'Screenshot%20from%202025-09-20%...,None,None
41,27665,6,wagner.bento,1753850224000,1753850224000,### Turno de Estudos de Máquina:\n'\n+ **19h02...,[],2025-07-30T22:02:00.000000Z,2025-07-30T09:20:00.000000Z
44,24582,2,wagner.bento,1733434240000,1733434239000,Observamos pequenas pertubações nos dois plano...,"[{'fileName': 'sisimografo_051224.pdf', 'conte...",None,None
45,22953,1,wagner.bento,1721363213000,1721363213000,### Turno de Operação:\n'\n+ **21h00:** Reboot...,[],2024-07-20T00:00:00.000000Z,2024-07-20T02:06:00.000000Z

In [57]:
new_df = df.copy()

new_df.loc[8, "from"] = "2024-06-26T22:46:38.000000Z"
new_df.loc[8, "to"]   = "2024-06-27T00:46:38.000000Z"

new_df = new_df.drop(35, )

new_df.loc[36, "from"] = "2025-10-31T18:51:12.000000Z"
new_df.loc[36, "to"]   = "2025-10-31T20:51:12.000000Z"

new_df.loc[38, "from"] = "2025-09-18T19:00:00.000000Z"
new_df.loc[38, "to"]   = "2025-09-18T23:00:00.000000Z"

new_df.loc[44, "from"] = "2024-12-05T19:00:00.000000Z"
new_df.loc[44, "to"]   = "2024-12-05T23:00:00.000000Z"

new_df.to_csv("olog_data.csv", index=False)

new_df

,id,version,owner,createdDate,eventStart,description,attachments,from,to
0,34292,2,alex.cavalcante,1791606683000,1791579600000,**Oscilaçôes no feixe devido a abalos sísmicos...,"[{'fileName': 'QUAKE DETAILS.png', 'contentTyp...",2026-10-09T20:25:00.000000Z,2026-10-09T21:00:00.000000Z
1,34291,1,vanusa.souza,1791580202000,1791580202000,### **Turno de usuários**\n\n\n\n\n- 04h23: Oc...,[],2026-10-09T07:23:00.000000Z,2026-10-09T10:41:00.000000Z
2,34284,4,wagner.bento,1791575366000,1791570239000,#### Oscilação no feixe devido a ocorrencia de...,[{'fileName': 'Screenshot from 2026-10-09 16-2...,2026-10-09T18:13:37.000000Z,2026-10-09T18:23:59.000000Z
3,33387,2,vanusa.souza,1787257212000,1787257212000,##### **Oscilaçôes no feixe- possível influênc...,[{'fileName': 'Screenshot from 2026-08-20 16-1...,2026-08-20T18:00:00.000000Z,2026-08-20T20:00:00.000000Z
4,33338,1,alex.cavalcante,1786782933000,1786752000000,**Oscilaçôes no feixe devido a abalos sísmicos...,"[{'fileName': 'QUAKE_INDONESIA.png', 'contentT...",2026-08-15T22:00:00.000000Z,2026-08-16T00:00:00.000000Z
5,33266,5,lucas.ransato,1786392909000,1786365268000,"**Terremoto na Colômbia - San José del Palmar,...",[{'fileName': 'Screenshot from 2026-08-10 17-1...,2026-08-10T12:34:28.000000Z,2026-08-10T14:34:28.000000Z
6,33005,6,daniel.cantarani,1785241701000,1785241701000,### Terremoto no Japão\n.\n- Por volta de 07h4...,[{'fileName': 'SismÃ³grafo terremoto Japan.PNG...,2026-07-28T07:27:00.000000Z,2026-07-28T09:27:00.000000Z
7,32807,2,wagner.bento,1784309897000,1784309897000,**TERREMOTO - EVENTO SÍSMICO DETECTADO** \n\n-...,[{'fileName': 'Screenshot from 2026-07-17 14-3...,2026-07-17T15:06:00.000000Z,2026-07-17T15:47:00.000000Z
8,32454,6,carlos.vieira,1782374640000,1782374640000,### Oscilações no feixe por Abalos Sísmicos\n'...,"[{'fileName': 'image_1782374640200.png', 'cont...",2024-06-26T22:46:38.000000Z,2024-06-27T00:46:38.000000Z
9,32189,3,alex.cavalcante,1780908433000,1780880400000,**Oscilaçôes no feixe por abalos sísmicos**\n\...,"[{'fileName': 'quake0706.png', 'contentType': ...",2026-06-08T23:37:00.000000Z,2026-06-09T01:37:00.000000Z
10,30916,4,wagner.bento,1774000537000,1773972000000,#### Oscilaçôes no feixe por abalos sísmicos\n...,"[{'fileName': 'quake.PNG', 'contentType': 'ima...",2026-03-21T00:22:00.000000Z,2026-03-21T01:15:00.000000Z
11,30766,5,vanusa.souza,1773419114000,1773419113000,##### **TERREMOTO - EVENTO SÍSMICO DETECTADO ...,"[{'fileName': 'Capturar.PNG', 'contentType': '...",2026-03-13T13:49:00.000000Z,2026-03-13T13:55:00.000000Z
12,28551,4,alex.cavalcante,1758779994000,1758772800000,## Terremoto 2 (Venezuela)\nNovo terremoto na ...,[{'fileName': 'Screenshot 2025-09-25 at 03-32-...,2025-09-25T03:58:00.000000Z,2025-09-25T05:58:00.000000Z
13,28549,3,alex.cavalcante,1758758030000,1758753722000,## Terremoto (Venezuela)\nOs BPMs apresentaram...,"[{'fileName': 'quakeVen.PNG', 'contentType': '...",2025-09-24T22:18:00.000000Z,2025-09-24T22:42:00.000000Z
14,28375,1,alex.cavalcante,1757758631000,1757736840000,"Entre 00h52 e 01h15, os BPMs horizontais apres...",[{'fileName': 'Screenshot 2025-09-13 at 06-59-...,2025-09-13T03:52:00.000000Z,2025-09-13T04:15:00.000000Z
15,28009,5,vanusa.souza,1755834161000,1755834160000,"- Entre 23h30 e 23h55, os BPMs horizontais apr...",[{'fileName': 'Screenshot 2025-08-22 at 00-37-...,2025-08-23T02:16:00.000000Z,2025-08-23T02:55:00.000000Z
16,27663,2,wagner.bento,1753848445000,1753839300000,"Durante os estudos de máquina, pessoal do grup...",[{'fileName': 'Screenshot from 2025-07-30 01-0...,2025-07-30T04:36:01.597000Z,2025-07-30T04:46:01.597000Z
17,27213,3,vanusa.souza,1751110563000,1751110563000,Houve pertubações nos BPMs do Anel nos planos ...,[{'fileName': 'Screenshot%20from%202025-06-28%...,2025-06-28T08:32:00.000000Z,2025-06-28T10:32:00.000000Z
18,26531,3,wagner.bento,1746213283000,1746190680000,Tivemos pequenas pertubações na órbita do feix...,[{'fileName': 'Screenshot from 2025-05-02 16-1...,2025-05-02T13:02:10.500000Z,2025-05-02T14:02:10.500000Z
19,26528,4,wagner.bento,1746195497000,1746195497000,### Turno de Usuários:\n'\n+ **09h45:** Terrem...,[{'fileName': 'Screenshot from 2025-05-02 12-2...,2025-05-02T12:45:00.000000Z,2025-05-02T17:00:00.000000Z
20,25307,4,carlos.vieira,1739074035000,1739074035000,### Pertubações na órbita Horizontal e Vertica...,"[{'fileName': 'BPMs.jpg', 'contentType': 'imag...",2025-02-09T23:23:00.000000Z,2025-02-09T23:40:00.000000Z
21,24692,3,alex.cavalcante,1734167413000,1734133273000,"Entre 20h43 e 21h00, os BPMs horizontais apres...","[{'fileName': 'earthquake.jpg', 'contentType':...",2024-12-13T23:43:00.000000Z,2024-12-14T00:00:00.000000Z
22,22946,4,wagner.bento,1721360690000,1721354100000,Houve pertubações nos [**BPMs**](https://ais-e...,[{'fileName': 'Sis_Chile_BPMs_OrbXY_180724.JPG...,2024-07-19T01:54:13.886Z,2024-07-19T01:59:13.886Z
23,22785,2,alex.cavalcante,1719656186000,1719645720000,Entre 04h22 E 04h28 alguns setores de bpms ho...,[{'fileName': 'Captura de tela 2024-06-29 0714...,2024-06-29T07:22:00.000000Z,2024-06-29T07:28:00.000000Z
36,29076,2,wagner.bento,1761955456000,1761936446000,"Houve um pequeno abalo sísmico, os [**BPMs do ...",[{'fileName': 'Screenshot%20from%202025-10-31%...,2025-10-31T18:51:12.000000Z,2025-10-31T20:51:12.000000Z
38,28472,3,walter.junior,1758388544000,1758225900000,"## Anotação tardia##\nSegue em anexo, gráficos...",[{'fileName': 'Screenshot%20from%202025-09-20%...,2025-09-18T19:00:00.000000Z,2025-09-18T23:00:00.000000Z
41,27665,6,wagner.bento,1753850224000,1753850224000,### Turno de Estudos de Máquina:\n'\n+ **19h02...,[],2025-07-30T22:02:00.000000Z,2025-07-30T09:20:00.000000Z
44,24582,2,wagner.bento,1733434240000,1733434239000,Observamos pequenas pertubações nos dois plano...,"[{'fileName': 'sisimografo_051224.pdf', 'conte...",2024-12-05T19:00:00.000000Z,2024-12-05T23:00:00.000000Z
45,22953,1,wagner.bento,1721363213000,1721363213000,### Turno de Operação:\n'\n+ **21h00:** Reboot...,[],2024-07-20T00:00:00.000000Z,2024-07-20T02:06:00.000000Z